import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

export const translations = {
  ar: {
    alliance: "ALLIANCE",
    loginText: "تسجيل الدخول",
    passwordPlaceholder: "الرمز السري...",
    musicStop: "إيقاف الموسيقى",
    musicPlay: "تشغيل الموسيقى",
    musicLabel: "الموسيقى",
    battlePlanTitle: "خطة معركة قلعة الملك",
    planProtectedTitle: "الخطة محمية",
    planProtectedDesc: "بحاجة إلى تسجيل الدخول من أجل رؤية الخطة",
    contactLeader: "لطلب كلمة السر تواصل مع القائد",
    introTitle: "المقدمة",
    battleDuration: "المعركة تستمر",
    hours5: "5 ساعات",
    requiredDuration: "المطلوب ساعتين ونصف",
    importantInstructions: "تعليمات هامة للمعركة",
    instruction1: "الانتباه للتعليمات والتواصل وقت المعركة.",
    instruction2: "ممنوع ارسال قوات مستوى 8 او اقل الى قلعة الملك.",
    instruction3: "استمر في تعزيز المشاة والفرسان فقط والشفاء دوماً عندما تكون في قلعة الملك او الابراج.",
    instruction4: "شفاء القوات يكون من خلال مساعدة التحالف.",
    watchVideo: "ملاحظة: يوصي بمشاهدة هذا الفيديو للتعلم:",
    swapHeroes: "استبدال الابطال:",
    swapHeroesDesc: "بعد الهجوم الناجح ارسل جورودن او هاورد للدفاع / قبل وصوله بقليل اسحب تشينكو ليدخل بطل دفاعي.",
    enemiesTitle: "الخصوم",
    enemyAlliances: "(التحالفات المعادية)",
    allianceDSN: "تحالف DSN",
    dsnStats: "يمتلكون",
    persons15: "15 شخص",
    hasT9: "لديه قوات T9.",
    allianceKGM: "تحالف KGM",
    persons21: "21 شخص",
    whalesWarning: "هؤلاء هم الحيتان الأقوى ضدنا، وهم الخطر الأكبر ويجب التعاون للتصدي لهجماتهم.",
    mainFormation: "التشكيل الأساسي",
    castleLeaders: "قادة قلعة الملك",
    towerLeaders: "قادة الأبراج",
    castleMainSupporters: "داعمين قلعة الملك الأساسي",
    importantNote: "ملاحظة هامة",
    importantNoteDesc: "هؤلاء داعمين قلعة الملك الأساسي. في حالة كانت قلعة الملك ممتلئة، يرجى الذهاب ودعم الأبراج.",
    towerSupporters: "داعمين الأبراج",
    mobileRole: "دور متحرك",
    noTimeRole: "يتحرك حسب الظروف بين أن يساعد في استعادة قلعة الملك في رالي مزدوج مع Percival واحتلال الأبراج.",
    lanceHiroRole: "يتحرك بين دعم قلعة الملك بقواته من المستوى 10 واحتلال الابراج (حسب الظروف).",
    warningToAll: "تنبيه هام للجميع",
    warningToAllDesc: "يجب على الأعضاء الانقسام وتوزيع الدعم على عدة أماكن (الأبراج وقلعة الملك) وعدم الذهاب فقط إلى قلعة الملك.",
    playersDistributionTitle: "توزيع أماكن اللاعبين",
    inFrontRow: "في المقدمة 6 مقاعد (قادة الحرب)",
    centerPlayers: "Percival و no time في المنتصف",
    distributionChart: "رسم بياني لتمركز اللاعبين",
    kingCastle: "قلعة الملك",
    northTower: "البرج الشمالي",
    westTower: "البرج الغربي",
    eastTower: "البرج الشرقي",
    southTower: "البرج الجنوبي",
    troopsPosition: "تمركز القوات",
    behindWarLeaders: "خلف قادة الحرب",
    behindWarLeadersDesc: "يتمركز قلاع من يمتلك",
    troops9_10: "قوات مستوى 9/10",
    onlyCastleEnterers: "، حيث هم الوحيدون من يدخلون قلعة الملك.",
    secondLine: "الخط الثاني",
    secondLineDesc: "يتمركز",
    troops8_9: "قوات مستوى 8/9",
    towerSupportNote: "(تدعيم الأبراج).",
    thirdLine: "الخط الثالث",
    thirdLineDesc: "بالخلف",
    troops8: "قوات المستوى 8",
    noCastleEntry: "ممنوع دخول قلعة الملك",
    prepareForce: "تجهيز القوة",
    warLeadersPower: "على",
    warLeadersLabel: "قادة الحرب",
    warLeadersPowerDesc: "وجميع من يمتلك الصلاحية تشغيل بافات تعزيز القوة.",
    reduceEnemyPower: "تفعيل قدرات",
    reduceEnemyPowerLabel: "خفض قوة العدو",
    reduceEnemyPowerDesc: "(Debuffs) لإضعاف خصومنا.",
    mandatoryAction: "هذا الإجراء",
    mandatoryLabel: "أساسي وإلزامي",
    mandatoryDesc: "لرفع كفاءتنا العسكرية في الهجوم والدفاع.",
    siegeWarning: "تنبيه حصار",
    dsnWarning: "الحذر من خبث",
    dsnLabel: "تحالف DSN",
    dsnWarningDesc: "ومحاولة تشتيت الإنتباه.",
    fakeAttack1: "من خلال التجسس أو الهجوم من خلال جندي واحد أو صنع رالي على قادة الحرب.",
    fakeAttack2: "جميع ما سيحدث من هذا هو هجوم وهمي لتشتيت الإنتباه.",
    fakeAttack3: "لا يجب النظر إليه أو القلق حياله.",
    battleStartA: "بداية المعركة A",
    entryRace: "سباق الدخول",
    entryRaceDesc: "يذهبون كلاهما بهجوم فردي مع تعزيز سرعة المسير القصوى للدخول أولا دون أي تأخير.",
    ymfalexWarning: "قد يفعل ذلك",
    ymfalexLabel: "Ymfalex115",
    ymfalexWarningDesc: "أيضاً، مع أي تأخير تعني فشل الهجوم الفردي الأول.",
    occupyTowers: "احتلال الابراج",
    bodanAction1: "يذهب بشكل فردي من اجل ان يحتل البرج الجنوبي ويكون قائد هذا البرج طوال فترة المعركة ، حيث يطرد القوات الخطأ هو بمساعدة r5",
    yunAction1: "يذهب بشكل فردي من اجل ان يحتل البرج الشرقي ويكون قائد هذا البرج طوال فترة المعركة ، حيث يطرد القوات الخطأ هو بمساعدة r5",
    lanceAction1: "ينتظر ما سوف يحدث قليلاً ، في حال سيطرنا على قلعة الملك والبرج الشرقي والغربي ينتظر افضل القوات تدخل على تلك الأماكن ، ثم يفتح رالي على البرج الشمالي يجمع بين قوات 8 و 9 من أجل أخذ البرج الشمالي.",
    castleCommand: "قيادة القلعة (Percival)",
    castleLeaderDesc1: "قائد قلعة الملك سيكون",
    percivalLabel: "Percival",
    castleLeaderDesc2: ". يحصل على دعم القوات الأساسية",
    troops9_10_only: "مستوى 9/10 فقط",
    requiredHeroes: "الأبطال المطلوبين",
    percivalWarning1: "يجب تشكيل القوات الصحيحة لأن Percival يمتلك إحصائيات مشاة وفرسان 50%-50%",
    percivalWarning2: "ممنوع رمي الرماة بشكل نهائي !!",
    ralliesTitle: "انشاء الراليات",
    rallyRule1: "يجب علي جميع اعضاء التحالف ارسال القوات للمنظمين بالوقت المحدد وعدم التاخير، يجب علي الجميع التواجد فى الوقت وعدم التأخير.",
    firstRally: "الرالي الأول",
    noTimeDesc: "يقوم 'no time' بإنشاء رالي على قلعة الملك، يطلب فيه قوات مستوى 9 أو 10 حصراً، ويجب دخول الرالي بأبطال الدفاع مثل جورودن وهاورد او هجوم، مع التأكد من عدم إرسال الرماة نهائياً.",
    heroWarning: "يجب اختيار الابطال بشكل صحيح اثناء الدخول في الدعم من الافضل دعم ب ابطال دفاع مثل  جورودن ، هاوارد",
    waitLabel: "ينتظر قليلاً",
    secondRally: "الرالي الثاني",
    lanceRallyDesc: "ينشئ LanceHiro رالي على البرج الشمالي ويطلب قوات مستوى 8 أو 9، ويجب على الجميع الدخول بسرعة.",
    time35: "35 دقيقة من المعركة",
    rallyRotation: "تبديل الراليات",
    rallyRotationDesc: "في حال لم نسيطر على قلعة الملك، يُلغى الرالي الأول. ثم يقوم Percival بإنشاء رالي قوي جداً للاستيلاء على القلعة.",
    supportReminder: "يجب تعويض القوات في وقت الراليات من اجل عدم خساره القلعة او الابراج من الدعم.",
    goodLuck: "- MOUSA -",
    languageButton: "English",
    loading: "جاري التحميل...",
    loginSuccess: "تم تسجيل الدخول بنجاح",
    loginError: "كلمة المرور خاطئة",
    playerPlacement: "توزيع أماكن اللاعبين",
    placementChart: "رسم بياني لتمركز اللاعبين",
    kingCastleTitle: "قلعة الملك",
    northTowerChart: "البرج\nالشمالي",
    westTowerChart: "البرج\nالغربي",
    eastTowerChart: "البرج\nالشرقي",
    southTowerChart: "البرج\nالجنوبي",
    frontRowLeaders: "في المقدمة 6 مقاعد (قادة الحرب)",
    midLeaders: "بيرسيفال و no time في المنتصف",
    troopPlacement: "تمركز القوات",
    behindLeaders: "خلف قادة الحرب",
    behindLeadersDesc: "يتمركز قلاع من يمتلك قوات مستوى 9/10، حيث هم الوحيدون من يدخلون قلعة الملك.",
    secondLine: "الخط الثاني",
    secondLineDesc: "يتمركز قوات مستوى 8/9",
    secondLineNote: "(تدعيم الأبراج).",
    thirdLine: "الخط الثالث",
    thirdLineDesc: "بالخلف قوات المستوى 8",
    thirdLineNote: "ممنوع دخول قلعة الملك",
    powerPrep: "تجهيز القوة",
    powerPrep1: "على قادة الحرب وجميع من يمتلك الصلاحية تشغيل بافات تعزيز القوة.",
    powerPrep2: "تفعيل قدرات خفض قوة العدو (Debuffs) لإضعاف خصومنا.",
    powerPrep3: "هذا الإجراء أساسي وإلزامي لرفع كفاءتنا العسكرية في الهجوم والدفاع.",
    siegeWarning: "تنبيه حصار",
    siegeCheck1: "الحذر من خبث تحالف DSN ومحاولة تشتيت الإنتباه.",
    siegeCheck2: "من خلال التجسس أو الهجوم من خلال جندي واحد أو صنع رالي على قادة الحرب.",
    siegeCheck3: "جميع ما سيحدث من هذا هو هجوم وهمي لتشتيت الإنتباه.",
    lanceHiroTowerRole: "ينتظر ما سوف يحدث قليلاً ، في حال سيطرنا على قلعة الملك والبرج الشرقي والغربي ينتظر افضل القوات تدخل على تلك الأماكن ، ثم يفتح رالي على البرج الشمالي يجمع بين قوات 8 و 9 من أجل أخذ البرج الشمالي.",
    castleLeadershipTitle: "قيادة القلعة (بيرسيفال)",
    castleLeaderRole: "قائد قلعة الملك سيكون بيرسيفال. يحصل على دعم القوات الأساسية مستوى 9/10 فقط.",
    kickWarning: "بيرسيفال و r5 وحده يتحكم في إخراج القوات الغير مناسبة في قلعة الملك",
    defenseFormation: "تشكيل قوات الدفاع",
    infantry: "مشاة",
    cavalry: "فرسان",
    marksmen: "رماة",
    planB: "الخطة B (استعادة القلعة)",
    planBDesc: "في حال واجهنا مشاكل في الخطة A وخسرنا قلعة الملك، سنقوم بصنع رالي مزدوج في نفس الثانية:",
    supportedBy: "مدعومة بقوات 9 و 10 من الأعضاء:",
    mainHero: "البطل الرئيسي - دعم الرالي للهجوم",
    attackFormation: "تشكيل جنود الهجوم",
    sure100: "هذا الشيء مؤكد 100% من أجل استعادة قلعة الملك بعد خسارتها.",
    planBRecoverTowers: "الخطة B (استعادة الأبراج)",
    counterAttack: "هجوم مضاد (رالي)",
    counterAttackDesc: "في حال خسارة الابراج فتح رالي من قبل قادة الابراج (보단이 ، 云公馆 ، LanceHiro) مدعومة بقوات مستوى 9/8 من اجل استعادة كل واحد برجه الموصي به.",
    towersBuff: "الابراج تمنح قائد قلعة الملك زيادة في القوة الدفاعية والهجومية",
    leadershipInstructions: "تعليمات القيادة",
    duringAndAfter: "أثناء وبعد المعركة",
    r4Instructions: "تعليمات R4",
    r4Rule1: "توجيه الأعضاء وإرشادهم لفعل الشيء الصحيح وتجنب الأخطاء.",
    r4Rule2: "يحق لهم إزالة الأعضاء الذين لا يستمعون للتعليمات.",
    r4Rule3: "يتم تطبيق هذا الإجراء بشكل خاص على من يمتلك قوات مستوى أقل من 8 في حال الاستمرار بالخطأ.",
    afterOccupation: "بعد احتلال قلعة الملك",
    afterOccupationNote: "(يحدث هذا بعد مرور ساعتين ونصف)",
    afterOcc1: "ضمان الفوز وتحقيق الهدف الأساسي للمعركة.",
    afterOcc2: "يتحول القتال إلى قتال ودي لحصد النقاط وكسب المكافآت.",
    afterOcc3: "يُسمح لجميع الأعضاء بالدخول إلى قلعة الملك والتصرف بحرية.",
    youtubeModalTitle: "فيديو تعليمي"
  },
  en: {
    alliance: "ALLIANCE",
    loginText: "Login",
    passwordPlaceholder: "Password...",
    musicStop: "Stop Music",
    musicPlay: "Play Music",
    musicLabel: "Music",
    battlePlanTitle: "King Castle Battle Plan",
    planProtectedTitle: "Plan is Protected",
    planProtectedDesc: "You need to log in to view the plan",
    contactLeader: "To get the password, contact leader",
    introTitle: "Introduction",
    battleDuration: "The battle lasts",
    hours5: "5 Hours",
    requiredDuration: "Focus required for 2.5 hours",
    importantInstructions: "Important Battle Instructions",
    instruction1: "Pay attention to instructions and communicate during the battle.",
    instruction2: "It's forbidden to send tier 8 troops or lower to the King Castle.",
    instruction3: "Continue to reinforce infantry and cavalry only, and always heal when in the King Castle or Towers.",
    instruction4: "Troops healing is done through alliance aid.",
    watchVideo: "Note: It's recommended to watch this video to learn:",
    swapHeroes: "Swap Heroes:",
    swapHeroesDesc: "After a successful attack, send جورودن or هاورد for defense / just before he arrives, recall تشينكو to let a defense hero enter.",
    enemiesTitle: "Enemies",
    enemyAlliances: "(Hostile Alliances)",
    allianceDSN: "DSN Alliance",
    dsnStats: "They have",
    persons15: "15 members",
    hasT9: "with T9 troops.",
    allianceKGM: "KGM Alliance",
    persons21: "21 members",
    whalesWarning: "These are the strongest whales against us, they are the biggest threat and we must cooperate to counter their attacks.",
    mainFormation: "Main Formation",
    castleLeaders: "King Castle Leaders",
    towerLeaders: "Tower Leaders",
    castleMainSupporters: "Main King Castle Supporters",
    importantNote: "Important Note",
    importantNoteDesc: "These are the main King Castle supporters. If the King Castle is full, please go and support the towers.",
    towerSupporters: "Tower Supporters",
    mobileRole: "Mobile Role",
    noTimeRole: "Moves according to the situation between helping retake the King Castle in a double rally with Percival and occupying the towers.",
    lanceHiroRole: "Moves between supporting the King Castle with his T10 troops and occupying the towers (depending on the situation).",
    warningToAll: "Important Warning For All",
    warningToAllDesc: "Members must split up and distribute support to multiple places (Towers and King Castle) and not go exclusively to the King Castle.",
    playersDistributionTitle: "Players Distribution",
    inFrontRow: "In the front row 6 seats (War Leaders)",
    centerPlayers: "Percival and no time in the center",
    distributionChart: "Players Distribution Chart",
    kingCastle: "King Castle",
    northTower: "North Tower",
    westTower: "West Tower",
    eastTower: "East Tower",
    southTower: "South Tower",
    troopsPosition: "Troops Positioning",
    behindWarLeaders: "Behind War Leaders",
    behindWarLeadersDesc: "Castles with",
    troops9_10: "T9/T10 troops",
    onlyCastleEnterers: "are positioned here, as they are the only ones entering the King Castle.",
    secondLine: "Second Line",
    secondLineDesc: "Positioned with",
    troops8_9: "T8/T9 troops",
    towerSupportNote: "(Tower support).",
    thirdLine: "Third Line",
    thirdLineDesc: "At the back with",
    troops8: "T8 troops",
    noCastleEntry: "Forbidden to enter King Castle",
    prepareForce: "Prepare Force",
    warLeadersPower: "The",
    warLeadersLabel: "War Leaders",
    warLeadersPowerDesc: "and all who have permission must activate power boost buffs.",
    reduceEnemyPower: "Activate",
    reduceEnemyPowerLabel: "Enemy Power Reduction",
    reduceEnemyPowerDesc: "(Debuffs) to weaken our enemies.",
    mandatoryAction: "This action is",
    mandatoryLabel: "basic and mandatory",
    mandatoryDesc: "to increase our military efficiency in attack and defense.",
    siegeWarning: "Siege Warning",
    dsnWarning: "Beware of the cunning of",
    dsnLabel: "DSN Alliance",
    dsnWarningDesc: "and their attempts to distract.",
    fakeAttack1: "Through scouting, attacking with one soldier, or setting a rally on the war leaders.",
    fakeAttack2: "All of this will be a fake attack to distract attention.",
    fakeAttack3: "You shouldn't look at it or worry about it.",
    battleStartA: "Battle Start A",
    entryRace: "Entry Race",
    entryRaceDesc: "Both go with a solo attack using maximum march speed boost to enter first without any delay.",
    ymfalexWarning: "",
    ymfalexLabel: "Ymfalex115",
    ymfalexWarningDesc: "might do this too, any delay means the failure of the first solo attack.",
    occupyTowers: "Occupy Towers",
    bodanAction1: "Goes solo to occupy the South Tower and be the leader of this tower throughout the battle, forcefully returning wrong troops with R5 help.",
    yunAction1: "Goes solo to occupy the East Tower and be the leader of this tower throughout the battle, forcefully returning wrong troops with R5 help.",
    lanceAction1: "Waits slightly to see what happens, if we control the King Castle, East and West towers, he waits for the best troops to enter those places, then opens a rally on the North Tower combining T8 and T9 troops to take the North Tower.",
    castleCommand: "Castle Command (Percival)",
    castleLeaderDesc1: "The King Castle leader will be",
    percivalLabel: "Percival",
    castleLeaderDesc2: ". He receives support from main troops",
    troops9_10_only: "T9/T10 ONLY",
    requiredHeroes: "Required Heroes",
    percivalWarning1: "The correct troops must be formed because Percival has 50%-50% infantry and cavalry stats.",
    percivalWarning2: "It is absolutely forbidden to send archers!!",
    ralliesTitle: "Creating Rallies",
    rallyRule1: "All alliance members must send troops to the organizers on time without delay, everyone must be present on time.",
    firstRally: "First Rally",
    noTimeDesc: "'no time' creates a rally on the King Castle, requesting ONLY T9 or T10 troops, and you must join the rally with defense heroes like جورودن and هاورد or attack heroes, making sure NOT to send any archers.",
    heroWarning: "You must choose heroes correctly when entering support. It's better to support with defense heroes like جورودن, هاورد.",
    waitLabel: "Waits a little",
    secondRally: "Second Rally",
    lanceRallyDesc: "LanceHiro creates a rally on the North Tower requesting T8 or T9 troops, everyone must join quickly.",
    time35: "35 minutes into the battle",
    rallyRotation: "Rally Rotation",
    rallyRotationDesc: "If we don't control the King Castle, the first rally is cancelled. Then Percival creates a very strong rally to take the Castle.",
    supportReminder: "Troops must be replaced during rallies to avoid losing the Castle or towers from lack of support.",
    goodLuck: "- MOUSA -",
    languageButton: "العربية",
    loading: "LOADING...",
    loginSuccess: "Login Successful",
    loginError: "Incorrect Password",
    playerPlacement: "Player Placement",
    placementChart: "Placement Chart",
    kingCastleTitle: "King Castle",
    northTowerChart: "North\nTower",
    westTowerChart: "West\nTower",
    eastTowerChart: "East\nTower",
    southTowerChart: "South\nTower",
    frontRowLeaders: "Front Row 6 seats (War Leaders)",
    midLeaders: "Percival and no time in the Middle",
    troopPlacement: "Troop Placement",
    behindLeaders: "Behind War Leaders",
    behindLeadersDesc: "Castles with T9/T10 troops are positioned here, the only ones entering the King Castle.",
    secondLine: "Second Line",
    secondLineDesc: "T8/T9 troops are stationed here",
    secondLineNote: "(Tower support).",
    thirdLine: "Third Line",
    thirdLineDesc: "T8 troops at the back",
    thirdLineNote: "Forbidden to enter King Castle",
    powerPrep: "Power Preparation",
    powerPrep1: "War leaders and authorized members must activate power buffs.",
    powerPrep2: "Activate enemy power reduction (Debuffs) to weaken opponents.",
    powerPrep3: "This action is mandatory to raise our military efficiency in attack and defense.",
    siegeWarning: "Siege Warning",
    siegeCheck1: "Beware of DSN alliance's malice and attempts to distract.",
    siegeCheck2: "Through scouting, attacking with one soldier, or setting a rally on war leaders.",
    siegeCheck3: "All of this will be a fake attack to distract attention.",
    lanceHiroTowerRole: "Waits slightly, if we control the King Castle, East and West towers, he waits for the best troops to enter, then opens a rally on the North Tower combining T8 and T9 troops.",
    castleLeadershipTitle: "Castle Command (Percival)",
    castleLeaderRole: "The King Castle leader will be Percival. He only receives support from T9/T10 troops.",
    kickWarning: "Percival and R5 alone control kicking unsuited troops in King Castle.",
    defenseFormation: "Defense Formation",
    infantry: "Infantry",
    cavalry: "Cavalry",
    marksmen: "Marksmen",
    planB: "Plan B (Castle Recovery)",
    planBDesc: "If we encounter problems in Plan A and lose the King Castle, we will perform a double rally at the exact same second:",
    supportedBy: "Supported by T9 and T10 troops from members:",
    mainHero: "Main Hero - Rally Support for Attack",
    attackFormation: "Attack Formation",
    sure100: "This is 100% certain in order to retake the King Castle after losing it.",
    planBRecoverTowers: "Plan B (Towers Recovery)",
    counterAttack: "Counter Attack (Rally)",
    counterAttackDesc: "If towers are lost, a rally is opened by tower leaders (보단이, 云公馆, LanceHiro) supported by T8/T9 troops to recover their respective tower.",
    towersBuff: "Towers grant the King Castle leader increased defensive and offensive power",
    leadershipInstructions: "Leadership Instructions",
    duringAndAfter: "During and After the Battle",
    r4Instructions: "R4 Instructions",
    r4Rule1: "Guide members and instruct them to do the right thing and avoid mistakes.",
    r4Rule2: "They have the right to remove members who don't listen to instructions.",
    r4Rule3: "This applies especially to those with troops below T8 if they persist in errors.",
    afterOccupation: "After Occupying King Castle",
    afterOccupationNote: "(This happens after two and a half hours)",
    afterOcc1: "Ensuring victory and achieving the primary goal of the battle.",
    afterOcc2: "The fight turns into a friendly fight to gather points and earn rewards.",
    afterOcc3: "All members are allowed to enter the King Castle and act freely.",
    youtubeModalTitle: "Tutorial Video"
  }
};

type TransKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: TransKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.title = language === 'ar' ? "معركة قلعة الملك" : "King Castle Battle";
  }, [language]);

  const t = (key: TransKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
